config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  authenticated :user do
    root "docs#index", as: "authenticated_root"
  end
  root 'welcome#index'
  resources :docs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
# frozen_string_literal: true

# Doc model
class Doc < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :docs
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application Controller class
class ApplicationController < ActionController::Base

end

app/controllers/docs_controller.rb
# frozen_string_literal: true

# Docs Controller class
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]

  def index
      @docs = Doc.where(user_id: current_user)
  end

  def show

  end

  def new
      @doc = current_user.docs.build
  end

  def create
      @doc = current_user.docs.build(doc_params)
      if @doc.save
          redirect_to @doc
      else
          render 'new'
      end
  end

  def edit

  end

  def update
      if @doc.update(doc_params)
          redirect_to @doc
      else
          render 'edit'
      end
  end

  def destroy
      @doc.destroy
      redirect_to docs_path
  end

  private
      def find_doc
          @doc = Doc.find(params[:id])
      end

      def doc_params
          params.require(:doc).permit(:title, :content)
      end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
  = f.input :title
  = f.input :content
  = f.button :submit, class: "button"

app/views/docs/edit.html.haml
.wrapper_with_padding
  %h1 Fix Doc!
  = render 'form'
  = link_to "Cancel", doc_path

app/views/docs/index.html.haml
.wrapper_with_padding
  #docs.cleafix
    - unless @docs.blank?
      - @docs.each do |doc|
        %a{ href: (url_for [doc])}
          .doc
            %p.title= doc.title
            %p.date= time_ago_in_words(doc.created_at)
            %p.content= truncate(doc.content, length:50)
    - else
      %h2 Create Doc!
      %p Start Creating Documents and Organizing Your %life!
      %button= link_to "Create Doc", new_doc_path

app/views/docs/new.html.haml
.wrapper_with_padding
  %h1 New Doc!
  = render 'form'

app/views/docs/show.html.haml
.wrapper_with_padding
  #doc_show
    %h1.title= @doc.title
    %p= simple_format(@doc.content)

    .buttons
      = link_to "Fix Doc", edit_doc_path(@doc), class: "button"
      = link_to "Trash It", doc_path(@doc), method: :delete, data: {confirm: 'Are you sure?'}, class: "button"

app/views/layouts/application.html.haml
!!!
%html
%head
  %title FileCabinet | Your life's work!
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = csrf_meta_tags
%body
  %header
    .header_inner
      = link_to "FileCabinet", root_path, id: "logo"
      %nav
        - if user_signed_in?
          = link_to "Create Doc", new_doc_path
          = link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          = link_to "Log In", new_user_session_path
  %p.notice= notice
  %p.alert= alert

  = yield

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 File Cabinet
    %p Your life's work. Organized, always.
    %button= link_to "Enter", new_user_registration_path

#callouts
  .callout_inner
    .wrapper
      .callout
        %h2 Organize
        %p Manage your showings wherever you are! Take CSS onthe road with our CSS Mobile App available for Androi& Apple. Create appointments and manage listings anshowings from your mobile device.

#bottom_cta
  .wrapper
    %h2 Go Ahead!
    %br
    %buttom= link_to "Join Now", new_user_registration_path